### ISSUE TITLE
Error when install composer

### ISSUE THREAD

**Issue by kimhour168** [ijpatricio/minglejs-demo#10]
![image](https://github.com/user-attachments/assets/55fef631-d1ef-4308-abbc-deeac5107917)
I got this error when I try to run composer install
step error:
1.clone
2. run composer install

**Comment by ijpatricio** [comment]
Hello @kimhour168 

Thank you! I'll be fixing this, and better yet, making better focused demos with real world app.

For now, you can solve it just by removing these lines:

![CleanShot 2024-10-16 at 14 22 20](https://github.com/user-attachments/assets/d2956c13-517d-4504-881d-b1c6f9049377)

If anything happens, let me know! thanks!

**Comment by kimhour168** [comment]
Thank you
