### ISSUE TITLE
Cannot assign float to property App\Livewire\LivewireCounter::$count of type int

### ISSUE THREAD

**Issue by kenanba** [ijpatricio/minglejs-demo#7]
Counter component with Livewire
Current Count: 2.2300745198530623e+43

**Comment by ijpatricio** [comment]
Hello. Can you explain the situation?

It doesn't seem to be related to Mingle.

What are you trying to achieve, and what code did you implement?

**Comment by kenanba** [comment]
Yes, you're correct. There's a type error in the Livewire component when I click the button (Double it - and give it to the next person) excessively.

https://minglejs-demo.unitedbycode.com/demo-with-livewire

**Comment by ijpatricio** [comment]
Hey.

Ooh, that's right, because the number eventually gets higher than the defined type.

I'll get it fixed, thanks!
