### ISSUE TITLE
Server-side Rendering of MingleJS Components

### ISSUE THREAD

**Issue by wescopeland** [ijpatricio/minglejs-demo#9]
One major benefit of LiveWire components is the HTML template is still sent to the browser on the initial render.

I can't help but notice that if JS is disabled on the demo site, the LiveWire component renders, but MingleJS components do not. One benefit of being able to use MingleJS would be to migrate components from the ground-up on a Blade/PHP page to React before fully migrating the page to be an Inertia.js route.

Is it possible to set up SSR on MingleJS components?

**Comment by ijpatricio** [comment]
Hey @wescopeland 

Livewire needs JS to be active. It will render the first time, but that's just like regular Blade. To be reactive, it needs the `livewire.js` part active.

I'm sure it's possible to achieve, just like in Inertia, but as of today, I'm afraid it's not, and I have no plans to make it.

If you need the whole JS to SSR, you should then make that page Inertia.
You can have a mix of them in the same project, but you seem to already know that, so this is probably not new.

Thanks for considering!
